# 应用部署根目录，代码将拉取到此目录的 releases 子目录
app_path: "/var/www/thinkphp"  

# 应用代码仓库地址，支持 HTTPS 或 SSH
app_repo: "https://gitee.com/top-think/think.git"  

# git_version 可以指定分支、标签或提交哈希来控制部署版本。
git_version: "8.x"  

# 绑定的域名，用于 Nginx 配置等
domain: www.thinkphp.com  

# 应用运行用户和用户组，确保权限正确
app_user: "www-data"  
app_group: "www-data"  

